@echo off
echo ============================================
echo XAU/USD Scalping System Setup
echo ============================================
echo.

echo 1. Creating requirements.txt...
echo flask==2.3.3 > requirements.txt
echo flask-socketio==5.3.4 >> requirements.txt
echo flask-cors==4.0.0 >> requirements.txt
echo MetaTrader5==5.0.43 >> requirements.txt
echo pandas==2.0.3 >> requirements.txt
echo python-dotenv==1.0.0 >> requirements.txt
echo.

echo 2. Installing Python packages...
pip install --upgrade pip
pip install flask flask-socketio flask-cors MetaTrader5 pandas python-dotenv
echo.

echo 3. Creating project structure...
mkdir -p logs
mkdir -p data
echo.

echo 4. Creating mt5_bridge.py...
(
echo import asyncio
echo import json
echo import logging
echo from datetime import datetime
echo from flask import Flask, jsonify, request
echo from flask_socketio import SocketIO, emit
echo from flask_cors import CORS
echo import MetaTrader5 as mt5
echo import pandas as pd
echo import threading
echo import time
echo import os
echo.
echo "# Configure logging"
echo "logging.basicConfig(level=logging.INFO)"
echo "logger = logging.getLogger(__name__)"
echo.
echo "class MT5Bridge:"
echo "    def __init__(self):"
echo "        self.app = Flask(__name__)"
echo "        CORS(self.app)"
echo "        self.socketio = SocketIO(self.app, cors_allowed_origins='*', async_mode='threading')"
echo "        self.mt5_connected = False"
echo "        self.account_info = None"
echo "        self.positions = []"
echo "        self.last_prices = {}"
echo "        "
echo "        # Setup routes"
echo "        self.setup_routes()"
echo "        self.setup_socket_events()"
echo "        "
echo "    def setup_routes(self):"
echo "        @self.app.route('/')"
echo "        def index():"
echo "            return jsonify({"
echo "                'status': 'MT5 Bridge Server Running',"
echo "                'mt5_connected': self.mt5_connected,"
echo "                'endpoints': {"
echo "                    '/connect': 'Connect to MT5',"
echo "                    '/account': 'Get account info',"
echo "                    '/positions': 'Get open positions',"
echo "                    '/symbols': 'Get available symbols',"
echo "                    '/price/<symbol>': 'Get symbol price'"
echo "                }"
echo "            })"
echo "        "
echo "        @self.app.route('/connect', methods=['POST'])"
echo "        def connect_mt5():"
echo "            try:"
echo "                data = request.json"
echo "                if not data:"
echo "                    return jsonify({'error': 'No data provided'}), 400"
echo "                "
echo "                # Initialize MT5"
echo "                if not mt5.initialize():"
echo "                    return jsonify({'error': 'MT5 initialization failed', 'last_error': mt5.last_error()}), 400"
echo "                "
echo "                # Login to account"
echo "                account = data.get('account', '')"
echo "                password = data.get('password', '')"
echo "                server = data.get('server', '')"
echo "                "
echo "                logger.info(f'Attempting to connect to MT5: Account={account}, Server={server}')"
echo "                "
echo "                authorized = mt5.login("
echo "                    login=int(account),"
echo "                    password=password,"
echo "                    server=server"
echo "                )"
echo "                "
echo "                if authorized:"
echo "                    self.mt5_connected = True"
echo "                    self.account_info = mt5.account_info()._asdict()"
echo "                    "
echo "                    # Start price monitoring"
echo "                    threading.Thread(target=self.monitor_prices, daemon=True).start()"
echo "                    "
echo "                    logger.info(f'Connected to MT5 successfully. Account: {self.account_info['login']}')"
echo "                    "
echo "                    return jsonify({"
echo "                        'success': True,"
echo "                        'message': f'Connected to MT5 account {self.account_info['login']}',"
echo "                        'account_info': self.account_info"
echo "                    })"
echo "                else:"
echo "                    mt5.shutdown()"
echo "                    return jsonify({"
echo "                        'error': 'MT5 login failed',"
echo "                        'last_error': mt5.last_error()"
echo "                    }), 401"
echo "                    "
echo "            except Exception as e:"
echo "                logger.error(f'Connection error: {e}')"
echo "                return jsonify({'error': str(e)}), 500"
echo "        "
echo "        @self.app.route('/account', methods=['GET'])"
echo "        def get_account():"
echo "            if not self.mt5_connected:"
echo "                return jsonify({'error': 'Not connected to MT5'}), 400"
echo "            "
echo "            try:"
echo "                account = mt5.account_info()._asdict()"
echo "                return jsonify(account)"
echo "            except Exception as e:"
echo "                return jsonify({'error': str(e)}), 500"
echo "        "
echo "        @self.app.route('/positions', methods=['GET'])"
echo "        def get_positions():"
echo "            if not self.mt5_connected:"
echo "                return jsonify({'error': 'Not connected to MT5'}), 400"
echo "            "
echo "            try:"
echo "                positions = mt5.positions_get()"
echo "                positions_data = []"
echo "                for pos in positions:"
echo "                    pos_dict = pos._asdict()"
echo "                    positions_data.append(pos_dict)"
echo "                "
echo "                self.positions = positions_data"
echo "                return jsonify(positions_data)"
echo "            except Exception as e:"
echo "                return jsonify({'error': str(e)}), 500"
echo "        "
echo "        @self.app.route('/trade', methods=['POST'])"
echo "        def execute_trade():"
echo "            if not self.mt5_connected:"
echo "                return jsonify({'error': 'Not connected to MT5'}), 400"
echo "            "
echo "            try:"
echo "                data = request.json"
echo "                symbol = data.get('symbol', 'XAUUSD')"
echo "                order_type = data.get('type', 'buy')"
echo "                volume = float(data.get('volume', 0.01))"
echo "                "
echo "                # Prepare the trade request"
echo "                if order_type == 'buy':"
echo "                    order_type_mt5 = mt5.ORDER_TYPE_BUY"
echo "                    price = mt5.symbol_info_tick(symbol).ask"
echo "                else:"
echo "                    order_type_mt5 = mt5.ORDER_TYPE_SELL"
echo "                    price = mt5.symbol_info_tick(symbol).bid"
echo "                "
echo "                request_dict = {"
echo "                    'action': mt5.TRADE_ACTION_DEAL,"
echo "                    'symbol': symbol,"
echo "                    'volume': volume,"
echo "                    'type': order_type_mt5,"
echo "                    'price': price,"
echo "                    'deviation': 10,"
echo "                    'magic': 234000,"
echo "                    'comment': 'Web Scalping',"
echo "                    'type_time': mt5.ORDER_TIME_GTC,"
echo "                    'type_filling': mt5.ORDER_FILLING_IOC,"
echo "                }"
echo "                "
echo "                result = mt5.order_send(request_dict)"
echo "                "
echo "                if result.retcode == mt5.TRADE_RETCODE_DONE:"
echo "                    return jsonify({"
echo "                        'success': True,"
echo "                        'order_id': result.order,"
echo "                        'message': 'Trade executed successfully'"
echo "                    })"
echo "                else:"
echo "                    return jsonify({"
echo "                        'success': False,"
echo "                        'error': result.comment"
echo "                    }), 400"
echo "                    "
echo "            except Exception as e:"
echo "                return jsonify({'error': str(e)}), 500"
echo "    "
echo "    def setup_socket_events(self):"
echo "        @self.socketio.on('connect')"
echo "        def handle_connect():"
echo "            logger.info(f'Web client connected')"
echo "            emit('connected', {'message': 'Connected to MT5 Bridge'})"
echo "        "
echo "    def monitor_prices(self):"
echo "        monitored_symbols = ['XAUUSD']"
echo "        "
echo "        while self.mt5_connected:"
echo "            try:"
echo "                for symbol in monitored_symbols:"
echo "                    tick = mt5.symbol_info_tick(symbol)"
echo "                    if tick:"
echo "                        price_data = {"
echo "                            'symbol': symbol,"
echo "                            'bid': tick.bid,"
echo "                            'ask': tick.ask,"
echo "                            'time': str(tick.time)"
echo "                        }"
echo "                        self.socketio.emit('price_update', price_data)"
echo "                time.sleep(1)"
echo "            except:"
echo "                time.sleep(5)"
echo "    "
echo "    def run(self, host='0.0.0.0', port=5000):"
echo "        logger.info(f'Starting MT5 Bridge Server on {host}:{port}')"
echo "        self.socketio.run(self.app, host=host, port=port, debug=True, allow_unsafe_werkzeug=True)"
echo.
echo "if __name__ == '__main__':"
echo "    bridge = MT5Bridge()"
echo "    bridge.run()"
) > mt5_bridge.py
echo.

echo 5. Creating mt5_scalping.html...
(
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "    <title>XAU/USD Scalping System</title>"
echo "    <style>"
echo "        body { font-family: Arial, sans-serif; margin: 20px; }"
echo "        .container { max-width: 1200px; margin: 0 auto; }"
echo "        .status { padding: 10px; margin: 10px 0; border-radius: 5px; }"
echo "        .connected { background: #d4edda; color: #155724; }"
echo "        .disconnected { background: #f8d7da; color: #721c24; }"
echo "        .dashboard { display: grid; grid-template-columns: 2fr 1fr; gap: 20px; }"
echo "        .panel { border: 1px solid #ddd; padding: 20px; border-radius: 5px; }"
echo "        button { padding: 10px 20px; margin: 5px; cursor: pointer; }"
echo "        .buy { background: #28a745; color: white; }"
echo "        .sell { background: #dc3545; color: white; }"
echo "    </style>"
echo "</head>"
echo "<body>"
echo "    <div class='container'>"
echo "        <h1>XAU/USD Scalping System</h1>"
echo "        <div id='status' class='status disconnected'>Disconnected</div>"
echo "        "
echo "        <div class='dashboard'>"
echo "            <div class='panel'>"
echo "                <h2>Price Chart</h2>"
echo "                <div id='price'>Loading...</div>"
echo "            </div>"
echo "            "
echo "            <div class='panel'>"
echo "                <h2>Trading</h2>"
echo "                <div>"
echo "                    <button class='buy' onclick='executeTrade(\"buy\")'>BUY</button>"
echo "                    <button class='sell' onclick='executeTrade(\"sell\")'>SELL</button>"
echo "                </div>"
echo "                <div id='positions'></div>"
echo "            </div>"
echo "        </div>"
echo "    </div>"
echo "    "
echo "    <script src='https://cdn.socket.io/4.6.0/socket.io.min.js'></script>"
echo "    <script>"
echo "        const socket = io('http://localhost:5000');"
echo "        "
echo "        socket.on('connect', () => {"
echo "            document.getElementById('status').className = 'status connected';"
echo "            document.getElementById('status').textContent = 'Connected to Bridge Server';"
echo "        });"
echo "        "
echo "        socket.on('price_update', (data) => {"
echo "            document.getElementById('price').innerHTML = `"
echo "                <h3>XAU/USD: $${data.bid.toFixed(2)}</h3>"
echo "                <p>Bid: $${data.bid.toFixed(2)} | Ask: $${data.ask.toFixed(2)}</p>"
echo "            `;"
echo "        });"
echo "        "
echo "        async function connectToMT5() {"
echo "            const response = await fetch('http://localhost:5000/connect', {"
echo "                method: 'POST',"
echo "                headers: { 'Content-Type': 'application/json' },"
echo "                body: JSON.stringify({"
echo "                    account: document.getElementById('account').value,"
echo "                    password: document.getElementById('password').value,"
echo "                    server: document.getElementById('server').value"
echo "                })"
echo "            });"
echo "            const data = await response.json();"
echo "            alert(data.message || data.error);"
echo "        }"
echo "        "
echo "        async function executeTrade(type) {"
echo "            const response = await fetch('http://localhost:5000/trade', {"
echo "                method: 'POST',"
echo "                headers: { 'Content-Type': 'application/json' },"
echo "                body: JSON.stringify({"
echo "                    symbol: 'XAUUSD',"
echo "                    type: type,"
echo "                    volume: 0.01"
echo "                })"
echo "            });"
echo "            const data = await response.json();"
echo "            alert(data.message || data.error);"
echo "        }"
echo "    </script>"
echo "</body>"
echo "</html>"
) > mt5_scalping.html
echo.

echo ============================================
echo Setup Complete!
echo ============================================
echo.
echo Next Steps:
echo 1. Make sure MT5 is installed and running
echo 2. Run the bridge server: python mt5_bridge.py
echo 3. Open mt5_scalping.html in your browser
echo 4. Enter your MT5 credentials
echo.
pause
